# Generated by Django 5.1.4 on 2025-02-21 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioVirgen', '0003_remove_listapodcastpendientes_programa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('numeroCuenta', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MetodoUsuario', to='radioVirgen.usuario')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo__in', ['Tarjeta', 'PayPal', 'Transferencia'])), name='check_tipo_values')],
            },
        ),
    ]
